# Generated by Django 3.0.2 on 2020-04-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poststepdrawingmodel',
            name='execution_time',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Время на выполнения'),
        ),
    ]
