# Generated by Django 3.0.2 on 2020-04-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0003_auto_20200418_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagespostdrawingmodel',
            name='steps',
            field=models.CharField(default=1, max_length=30, verbose_name='Шаг/Этап'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poststepdrawingmodel',
            name='video1',
            field=models.CharField(default=1, max_length=350, verbose_name='Видео 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poststepdrawingmodel',
            name='video2',
            field=models.CharField(default=1, max_length=350, verbose_name='Видео 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poststepdrawingmodel',
            name='video3',
            field=models.CharField(default=1, max_length=350, verbose_name='Видео 3'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagespostdrawingmodel',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='poststepdrawingmodel',
            name='level',
            field=models.CharField(choices=[('1', 'Легко'), ('2', 'Средне'), ('3', 'Сложно')], max_length=100, verbose_name='Уровень сложности'),
        ),
    ]
