# Generated by Django 3.0.2 on 2020-04-18 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0004_auto_20200418_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststepdrawingmodel',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='poststepdrawingmodel',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='poststepdrawingmodel',
            name='video3',
        ),
        migrations.CreateModel(
            name='VideoPostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=350, verbose_name='Видео')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='step_drawing.PostStepDrawingModel')),
            ],
            options={
                'verbose_name': 'Видео для поста обучения',
                'verbose_name_plural': 'Видео для поста обучения',
            },
        ),
    ]
