# Generated by Django 3.0.2 on 2020-04-19 09:27

from django.db import migrations, models
import step_drawing.models


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0006_auto_20200419_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorystepdrawingmodel',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=step_drawing.models.image_path_category, verbose_name='Осносное изображение'),
        ),
    ]
