# Generated by Django 3.0.2 on 2020-04-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0007_auto_20200419_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videopostmodel',
            old_name='video',
            new_name='frame',
        ),
        migrations.AddField(
            model_name='videopostmodel',
            name='name',
            field=models.CharField(default=1, max_length=250, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
