# Generated by Django 3.0.2 on 2020-04-19 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('step_drawing', '0005_auto_20200418_1658'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0003_comment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentStepDrawingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='comments.CommentStepDrawingModel')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_step_post', to='step_drawing.PostStepDrawingModel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments_step_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий пошаговое обучение',
                'verbose_name_plural': 'Комментарии пошаговое обучение',
                'ordering': ['created_at'],
            },
        ),
    ]
