# Generated by Django 3.0.2 on 2020-04-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_commentstepdrawingmodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentstepdrawingmodel',
            table='comment_step',
        ),
    ]
