# Generated by Django 3.0.2 on 2020-04-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0005_auto_20200419_1328'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='commentstepdrawingmodel',
            table='step_comments',
        ),
    ]
