# Generated by Django 3.0.2 on 2020-04-15 13:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 1')),
                ('text2', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 2')),
            ],
            options={
                'verbose_name': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex', models.TextField(blank=True, null=True, verbose_name='Метрика яндекса')),
                ('google_analytics', models.TextField(blank=True, null=True, verbose_name='Гугл аналитика')),
                ('google_adSense', models.TextField(blank=True, null=True, verbose_name='Гугл адсенс')),
            ],
            options={
                'verbose_name': 'Метрики, аналитики',
            },
        ),
        migrations.CreateModel(
            name='PostConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_post_days', models.PositiveSmallIntegerField(default=30, help_text='Кол-во дней пост считается новым (badge)', verbose_name='Дней')),
                ('post_popular', models.PositiveSmallIntegerField(default=500, help_text='Пост считается просматриваемый (badge)', verbose_name='Кол-во просмотров')),
                ('post_best', models.PositiveSmallIntegerField(default=10, help_text='Пост считается отлайканым (badge)', verbose_name='Кол-во лайков')),
            ],
            options={
                'verbose_name': 'Настройки поста',
            },
        ),
        migrations.CreateModel(
            name='ReklamaAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы верхний блок')),
                ('sidebar_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы сайтбар')),
            ],
            options={
                'verbose_name': 'Реклама все страницы',
            },
        ),
        migrations.CreateModel(
            name='ReklamaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы первый блок')),
                ('second_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы второй блок')),
                ('third_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы третий блок')),
                ('fourth_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы четвертый блок')),
                ('fifth_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы пятый блок')),
            ],
            options={
                'verbose_name': 'Реклама категории',
            },
        ),
        migrations.CreateModel(
            name='ReklamaPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы левый блок')),
                ('right_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы правый блок')),
                ('down_reklama_block', models.TextField(blank=True, null=True, verbose_name='Код рекламы нижний блок')),
            ],
            options={
                'verbose_name': 'Реклама посты',
            },
        ),
    ]
