# Generated by Django 3.0.2 on 2020-04-18 06:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepDrawingConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('text1', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Текст 1')),
            ],
            options={
                'verbose_name': 'Обучение настройка',
            },
        ),
    ]
