# Generated by Django 3.0.2 on 2020-04-19 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0002_stepdrawingconfiguration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stepdrawingconfiguration',
            table='step_config',
        ),
    ]
