# Generated by Django 3.0.2 on 2020-04-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0003_auto_20200419_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReklamaStepPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block1', models.TextField(blank=True, null=True, verbose_name='Первый блок')),
                ('block2', models.TextField(blank=True, null=True, verbose_name='Второй блок')),
                ('block3', models.TextField(blank=True, null=True, verbose_name='Третий блок')),
                ('block4', models.TextField(blank=True, null=True, verbose_name='Четвертый блок')),
                ('block5', models.TextField(blank=True, null=True, verbose_name='Пятый блок')),
                ('block6', models.TextField(blank=True, null=True, verbose_name='Шестой блок')),
                ('block7', models.TextField(blank=True, null=True, verbose_name='Седьмой блок')),
                ('block8', models.TextField(blank=True, null=True, verbose_name='Восьмой блок')),
            ],
            options={
                'verbose_name': 'Реклама пошаговые посты обучения',
                'db_table': 'step_reklama',
            },
        ),
    ]
